# Generated by Django 4.2.5 on 2023-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateBirth', models.DateTimeField()),
                ('identification', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('celphone', models.IntegerField()),
                ('residentialArea', models.CharField(max_length=100)),
                ('maritalStatus', models.CharField(max_length=100)),
                ('rh', models.CharField(max_length=100)),
                ('creed', models.CharField(max_length=100)),
            ],
        ),
    ]
