# Generated by Django 4.2.5 on 2023-10-01 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultorio', '0001_initial'),
        ('practicante', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('state', models.CharField(max_length=100)),
                ('id_consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.consultorio')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('id_practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicante.practicante')),
            ],
        ),
    ]
